main: com.Adawasda.skBetterModel.skBetterModel
api-version: 1.21
name: skBetterModel
authors: ['Adawasda']
description: A Skript addon
version: 1.0.1
website: https://no-website.net
# softdepend = optional dependency (won't crash if missing, but loads after these plugins)
# depend = required dependency (server won't start without it)
# Skript should be softdepend because we handle the missing check ourselves in onEnable()
softdepend: [Skript, BetterModel]
