main: com.Adawasda.skBetterModel.SkBetterModel
api-version: 1.21
name: skBetterModel
authors: ['Adawasda']
description: Skript addon for BetterModel integration
version: '@version@'
softdepend: [Skript, BetterModel]
